[date]
date_format = "%Y-%m-%d %H:%M"  # %Y: year, %m: month, %d: day, %H: hour, %M: minute. The time is always in UTC.

[repo]
show_public_repos = true  # Whether to show the count of public repositories.
show_private_repos = true  # Whether to show the count of private repositories.
show_collaborator_repo = true  # Whether to show the count of private repositories where you are a collaborator or repositories accessible through organizations you belong to.
# Set the format for displaying the repositories on the card.
# - "detail": 1 public 2 private 3 collabo repositories
#    - Items for which show_xxx_repos is set to false will not be displayed.
# - "total": Total 6 repositories
show_mode = "detail"

[commit]
include_private_commit = true  # Whether to include the commit count for private repositories.
show_commit_this_year = true  # Whether to show the commit count for this year.

[pr]
show_open_prs = true  # Whether to show the count of open pull requests.
show_merged_prs = true  # Whether to show the count of merged and closed pull requests.
show_closed_prs = true  # Whether to show the count of pull requests that are closed but not merged.
# Set the format for displaying the pull requests on the card.
# - "detail": 1 open 2 merged 3 closed(unmerged) PRs
# - "total": Total 6 PRs
show_mode = "detail"
